from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
import os

def generate_cam_pdf(company_name, final_score, recommendation, key_factors, output_path, llm_summary="", financial_ratios=None):
    """
    Generates a Credit Appraisal Memo (CAM) as a PDF, including LLM insights.
    """
    c = canvas.Canvas(output_path, pagesize=letter)
    width, height = letter
    
    # Title
    c.setFont("Helvetica-Bold", 20)
    c.drawString(50, height - 50, "Intelli Credit - Credit Appraisal Memo")
    
    # Company Info
    c.setFont("Helvetica", 14)
    c.drawString(50, height - 100, f"Company Name: {company_name}")
    
    # Score and Recommendation
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, height - 140, f"Credit Decision Score: {final_score}/100")
    
    if "Approved" in recommendation:
        c.setFillColor(colors.green)
    elif "Moderate" in recommendation:
        c.setFillColor(colors.darkorange)
    else:
        c.setFillColor(colors.red)
        
    c.drawString(50, height - 170, f"Recommendation: {recommendation}")
    c.setFillColor(colors.black)
    
    y = height - 220
    
    # LLM Executive Summary
    if llm_summary:
        c.setFont("Helvetica-Bold", 14)
        c.drawString(50, y, "Executive Summary:")
        c.setFont("Helvetica", 10)
        y -= 20
        # Simple text wrapping for prototype
        words = llm_summary.split()
        line = ""
        for word in words:
            if c.stringWidth(line + word, "Helvetica", 10) < width - 100:
                line += word + " "
            else:
                c.drawString(50, y, line)
                y -= 15
                line = word + " "
        c.drawString(50, y, line)
        y -= 30
        
    # Financial Ratios
    if financial_ratios:
        c.setFont("Helvetica-Bold", 14)
        c.drawString(50, y, "Extracted Financial Ratios:")
        c.setFont("Helvetica", 12)
        y -= 20
        for k, v in financial_ratios.items():
            name = k.replace("_", " ").title()
            c.drawString(70, y, f"- {name}: {v}")
            y -= 20
        y -= 10
    
    # Key Risk Factors
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y, "Key Risk & Data Factors:")
    
    c.setFont("Helvetica", 12)
    y -= 20
    for factor in key_factors:
        c.drawString(70, y, f"- {factor}")
        y -= 20
        
    # Footer
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(50, 50, "Generated by Intelli-Credit AI Prototype")
    
    c.save()
